<?php

namespace AppBundle\Repository;

/**
 * VendorSpecialDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorSpecialDayRepository extends \Doctrine\ORM\EntityRepository
{
}
