<?php

namespace AppBundle\Repository;

/**
 * VendorScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
